### PR TITLE
Add webpack

### PR DESCRIPTION
**Pull request by p-mazhnik**

### CODE REVIEW

**Comment by motiko** [comment]
Looks good. How about development cycle, we will need to build manually after each change?
Maybe we can add something like `watchmen` to simplify it?

**Comment by p-mazhnik** [comment]
` "dev": "webpack -w --config webpack.config.js --mode development"` ?

**Comment by motiko** [comment]
> ` "dev": "webpack -w --config webpack.config.js --mode development"` ?

Yes, just tried it. But for some reason css doesn't load

**Comment by p-mazhnik** [comment]
image

**Comment by p-mazhnik** [comment]
fixed

**Comment by motiko** [comment]
> image

we can add unsafe-eval for dev mode, i will take a look tmr or if you fix it first i will just merge it ;) .
got to go now. GN

**Pull request merged**
